/* crc32_chorba_mmi.c -- R5900 MMI non-destructive Chorba CRC-32 prototype.
 * For conditions of distribution and use, see copyright notice in zlib.h
 *
 * Based on Sam Russell, "Chorba: A novel CRC32 implementation"
 * https://arxiv.org/abs/2412.16398 (chorba_352 polynomial).
 *
 * The degree-44 reciprocal/reflect-polynomial identity
 *   Z(x) = x^44+x^39+x^37+x^28+x^13+x^12+x^9+x^7+x^3+x+1
 * is raised to its 128th power over GF(2), placing every tap on a
 * 16-byte boundary. The resulting look-ahead is 44*16 = 704 bytes.
 *
 * Every 16-byte block of input is XORed with pending contributions in a
 * 1024-byte power-of-two ring, then scattered to ten future positions
 * using EE LQ/PXOR/SQ. The 704-byte residue is reduced with the braid
 * implementation, then x^(704*8) is inverted with a precomputed matrix.
 *
 * All LQ/SQ addresses are aligned. Input is never modified. Short buffers
 * use the braid fallback. This option is experimental and OFF by default.
 */
#ifdef MIPS_MMI_CHORBA

#include "zbuild.h"
#include "arch_functions.h"

#define CHORBA_MMI_RING_BYTES 1024u
#define CHORBA_MMI_RING_MASK  (CHORBA_MMI_RING_BYTES - 1u)
#define CHORBA_MMI_RESIDUE    704u
#define CHORBA_MMI_THRESHOLD  4096u

/* Exponents 1,3,7,9,12,13,28,37,39,44 scaled by 16 bytes.
 * Note: the chronological offsets use the *low-to-high* polynomial
 * exponents, not (44-exponent). This matters for reflected CRC-32. */
static const uint16_t chorba_mmi_taps[10] = {
    16, 48, 112, 144, 192, 208, 448, 592, 624, 704
};

/* Columns of the inverse of the 704-byte zero-input CRC transition.
 * Generated by reversing 704 iterations of the zero-byte reflected
 * CRC32 step (polynomial 0xedb88320). */
static const uint32_t chorba_mmi_unshift_704[32] = {
    0x65ae920eu, 0xcb5d241cu, 0x4dcb4e79u, 0x9b969cf2u,
    0xec5c3fa5u, 0x03c9790bu, 0x0792f216u, 0x0f25e42cu,
    0x1e4bc858u, 0x3c9790b0u, 0x792f2160u, 0xf25e42c0u,
    0x3fcd83c1u, 0x7f9b0782u, 0xff360f04u, 0x251d1849u,
    0x4a3a3092u, 0x94746124u, 0xf399c409u, 0x3c428e53u,
    0x78851ca6u, 0xf10a394cu, 0x396574d9u, 0x72cae9b2u,
    0xe595d364u, 0x105aa089u, 0x20b54112u, 0x416a8224u,
    0x82d50448u, 0xdedb0ed1u, 0x66c71be3u, 0xcd8e37c6u
};

static inline uint32_t chorba_mmi_unshift(uint32_t value) {
    uint32_t result = 0;
    for (unsigned bit = 0; bit < 32; bit++)
        if ((value & (1u << bit)) != 0)
            result ^= chorba_mmi_unshift_704[bit];
    return result;
}

/* One ring scatter. target and block must be 16-byte aligned.
 * Keep the 128-bit value in an EE GPR only for the duration of the asm. */
static inline void chorba_mmi_xor_store(uint8_t *target, const uint8_t *block) {
    __asm__ volatile (
        "lq   $8, 0(%[value])\n\t"
        "lq   $9, 0(%[target])\n\t"
        "pxor $9, $9, $8\n\t"
        "sq   $9, 0(%[target])"
        :
        : [value] "r" (block), [target] "r" (target)
        : "$8", "$9", "memory"
    );
}

/* Pair two independent tap updates while retaining the 128-bit value
 * in a GPR instead of reloading it for every tap. Targets must be aligned.
 * The ten polynomial taps map to distinct slots in the 1024-byte ring. */
static inline void chorba_mmi_xor_store_pair(uint8_t *first, uint8_t *second,
                                             const uint8_t *block) {
    __asm__ volatile (
        "lq   $8, 0(%[value])\n\t"
        "lq   $9, 0(%[first])\n\t"
        "lq   $10, 0(%[second])\n\t"
        "pxor $9, $9, $8\n\t"
        "pxor $10, $10, $8\n\t"
        "sq   $9, 0(%[first])\n\t"
        "sq   $10, 0(%[second])"
        :
        : [value] "r" (block), [first] "r" (first), [second] "r" (second)
        : "$8", "$9", "$10", "memory"
    );
}

static uint32_t crc32_chorba_mmi_impl(uint32_t crc, const uint8_t *buf,
                                      size_t len, int paired, uint8_t *copydst) {
    size_t align = ((uintptr_t)buf & 15u);
    if (align != 0)
        align = 16u - align;

    if (len < CHORBA_MMI_THRESHOLD + align) {
        uint32_t result = crc32_braid(crc, buf, len);
        if (copydst != NULL && len != 0)
            memcpy(copydst, buf, len);
        return result;
    }

    if (align != 0) {
        crc = crc32_braid(crc, buf, align);
        if (copydst != NULL) {
            memcpy(copydst, buf, align);
            copydst += align;
        }
        buf += align;
        len -= align;
    }

    const size_t processed = len & ~(size_t)15u;
    uint8_t ring[CHORBA_MMI_RING_BYTES] ALIGNED_(16);
    uint8_t value[16] ALIGNED_(16);
    uint8_t first[16] ALIGNED_(16);
    uint8_t residue[CHORBA_MMI_RESIDUE] ALIGNED_(16);

    memset(ring, 0, sizeof(ring));
    memcpy(first, buf, sizeof(first));

    /* For a reflected CRC and >=4 input bytes, folding the raw seed
     * into the first four bytes converts a nonzero initial CRC state
     * into a zero-initial-state polynomial computation. */
    const uint32_t seed = ~crc;
    for (unsigned byte = 0; byte < 4; byte++)
        first[byte] ^= (uint8_t)(seed >> (byte * 8));

    for (size_t i = 0; i < processed; i += 16) {
        uint8_t *slot = ring + (i & CHORBA_MMI_RING_MASK);
        const uint8_t *src = i == 0 ? first : buf + i;

        /* XOR the current stream vector with all pending reductions. */
        if (copydst != NULL && i != 0 &&
            (((uintptr_t)(copydst + i) & 15u) == 0)) {
            /* Normal input blocks are unmodified; preserve original
             * 128-bit data with SQ before XORing in the ring contribution.
             * Block zero uses the seed-folded buffer and must instead
             * copy the original, unfurled bytes. */
            __asm__ volatile (
                "lq   $8, 0(%[src])\n\t"
                "sq   $8, 0(%[dst])\n\t"
                "lq   $9, 0(%[slot])\n\t"
                "pxor $8, $8, $9\n\t"
                "sq   $8, 0(%[value])"
                :
                : [src] "r" (src), [slot] "r" (slot),
                  [value] "r" (value), [dst] "r" (copydst + i)
                : "$8", "$9", "memory"
            );
        } else {
            __asm__ volatile (
                "lq   $8, 0(%[src])\n\t"
                "lq   $9, 0(%[slot])\n\t"
                "pxor $8, $8, $9\n\t"
                "sq   $8, 0(%[value])"
                :
                : [src] "r" (src), [slot] "r" (slot), [value] "r" (value)
                : "$8", "$9", "memory"
            );
            if (copydst != NULL)
                memcpy(copydst + i, buf + i, 16);
        }

        /* All future tap addresses are different from this slot.
         * Reclaim the current slot before the next modulo-ring cycle. */
        memset(slot, 0, 16);
        if (paired) {
            for (unsigned j = 0; j < 10; j += 2) {
                size_t first_offset = (i + chorba_mmi_taps[j]) & CHORBA_MMI_RING_MASK;
                size_t second_offset = (i + chorba_mmi_taps[j + 1]) & CHORBA_MMI_RING_MASK;
                chorba_mmi_xor_store_pair(ring + first_offset, ring + second_offset, value);
            }
        } else {
            for (unsigned j = 0; j < 10; ++j) {
                size_t target = (i + chorba_mmi_taps[j]) & CHORBA_MMI_RING_MASK;
                chorba_mmi_xor_store(ring + target, value);
            }
        }
    }

    /* Reassemble the 704 outstanding bytes in chronological order. */
    for (unsigned i = 0; i < CHORBA_MMI_RESIDUE; i += 16)
        memcpy(residue + i, ring + ((processed + i) & CHORBA_MMI_RING_MASK), 16);

    /* Starting with a zero raw CRC means passing ~0 as the public CRC.
     * The transformed stream has processed leading zero bytes, so only
     * its nonzero 704-byte residue contributes to the raw CRC. */
    uint32_t residue_raw = ~crc32_braid(~0u, residue, sizeof(residue));
    uint32_t result = ~chorba_mmi_unshift(residue_raw);

    /* Append the original unprocessed 0..15 byte suffix normally. */
    if (processed != len) {
        result = crc32_braid(result, buf + processed, len - processed);
        if (copydst != NULL)
            memcpy(copydst + processed, buf + processed, len - processed);
    }
    return result;
}

Z_INTERNAL uint32_t crc32_chorba_mmi_single(uint32_t crc, const uint8_t *buf,
                                             size_t len) {
    return crc32_chorba_mmi_impl(crc, buf, len, 0, NULL);
}

Z_INTERNAL uint32_t crc32_chorba_mmi_paired(uint32_t crc, const uint8_t *buf,
                                             size_t len) {
    return crc32_chorba_mmi_impl(crc, buf, len, 1, NULL);
}

Z_INTERNAL uint32_t crc32_chorba_mmi(uint32_t crc, const uint8_t *buf, size_t len) {
#ifdef MIPS_MMI_CHORBA_PAIRED_TAPS
    return crc32_chorba_mmi_paired(crc, buf, len);
#else
    return crc32_chorba_mmi_single(crc, buf, len);
#endif
}

Z_INTERNAL uint32_t crc32_copy_chorba_mmi_twopass(uint32_t crc, uint8_t *dst,
                                                  const uint8_t *src, size_t len) {
    uint32_t result = crc32_chorba_mmi(crc, src, len);
    if (len != 0)
        memcpy(dst, src, len);
    return result;
}

/* Only opt in to this fused path on hardware after timing. The original
 * byte stream, not the seed-folded first block, is copied to the output.
 * The function has the same non-overlap (memcpy) contract as the baseline. */
Z_INTERNAL uint32_t crc32_copy_chorba_mmi_fused(uint32_t crc, uint8_t *dst,
                                                 const uint8_t *src, size_t len) {
#ifdef MIPS_MMI_CHORBA_PAIRED_TAPS
    return crc32_chorba_mmi_impl(crc, src, len, 1, dst);
#else
    return crc32_chorba_mmi_impl(crc, src, len, 0, dst);
#endif
}

Z_INTERNAL uint32_t crc32_copy_chorba_mmi(uint32_t crc, uint8_t *dst,
                                          const uint8_t *src, size_t len) {
#ifdef MIPS_MMI_CHORBA_FUSED_COPY
    return crc32_copy_chorba_mmi_fused(crc, dst, src, len);
#else
    return crc32_copy_chorba_mmi_twopass(crc, dst, src, len);
#endif
}

#endif /* MIPS_MMI_CHORBA */
