# PS2DEV and PS2SDK may point to separate existing installations.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR mips)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(PS2DEV "$ENV{PS2DEV}" CACHE PATH "PS2 toolchain root")
set(PS2SDK "$ENV{PS2SDK}" CACHE PATH "PS2 SDK root")
if(NOT PS2DEV OR NOT EXISTS "${PS2SDK}/ee/startup/linkfile")
    message(FATAL_ERROR "Set PS2DEV and PS2SDK to your installed PS2 toolchain and SDK")
endif()
set(CMAKE_C_COMPILER "${PS2DEV}/ee/bin/mips64r5900el-ps2-elf-gcc")
if(EXISTS "${CMAKE_C_COMPILER}.exe")
    set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER}.exe")
endif()
set(PS2EE_CRT_DIR "${PS2DEV}/ee/mips64r5900el-ps2-elf/lib" CACHE PATH "Directory containing EE newlib crt0.o")
if(NOT EXISTS "${PS2EE_CRT_DIR}/crt0.o" AND EXISTS "${PS2SDK}/../ee/mips64r5900el-ps2-elf/lib/crt0.o")
    set(PS2EE_CRT_DIR "${PS2SDK}/../ee/mips64r5900el-ps2-elf/lib")
endif()
set(CMAKE_C_FLAGS_INIT "-D_EE -G0 -I${PS2SDK}/ee/include -I${PS2SDK}/common/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-B${PS2EE_CRT_DIR}/ -T${PS2SDK}/ee/startup/linkfile -L${PS2SDK}/ee/lib -Wl,-zmax-page-size=128")
set(CMAKE_EXECUTABLE_SUFFIX .elf)
# GCC's newlib specs use these SDK libraries for syscalls and startup.
set(CMAKE_C_STANDARD_LIBRARIES "-Wl,--start-group -lc -lcdvd -lcglue -lpthread -lpthreadglue -lkernel -Wl,--end-group")
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES PS2DEV PS2SDK PS2EE_CRT_DIR)

